version: '3.9'

services:
  db:
    image: mysql:8.1
    container_name: gestion-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345Guti
      MYSQL_DATABASE: gestion_protectora_pro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: gestion-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestion_protectora_pro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345Guti
    depends_on:
      - db

volumes:
  db-data:
